# Generated by Django 5.2.8 on 2025-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='if_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
