# Generated by Django 5.2.8 on 2025-11-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_if_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='if_cancelled',
            new_name='cancelled',
        ),
    ]
